### ISSUE TITLE
Problem building stamparm/pcapy-ng

### ISSUE THREAD

**Issue by ruffk** [vincentdavis/zwifty-packets#5]
I'm trying to build this extension but getting an error.  

- I'm using Visual Studio 2022 as my C compiler
- I downloaded the latest npcap sdk
- Before running Setup.py, I edited the include list to set the path to the sdk include folder

Several modules to compile fine, but pcapy.cc is throwing an error: 
pcapy.cc(272): error C2375: 'PyInit_pcapy': redefinition; different linkage

Any suggestions?

**Comment by vincentdavis** [comment]
@karthicksakkaravarti  Will, you add the readme details for building on windows or maybe include a built version of this.
@ruffk I think you need or can just download https://www.winpcap.org/ But let's see what Karthick says.

**Comment by karthicksakkaravarti** [comment]
Let me add readme file

**Comment by karthicksakkaravarti** [comment]
keep  wincap(https://www.winpcap.org/devel.htm) developer module under c:// path, and try to build it again . 

I'll update more detail steps in readme file later

**Comment by ruffk** [comment]
I just download the developer pack for winpcap and put it under c:\wpdpack.  Unfortunately I still get the same build error, again maybe related to using VS2022 compiler.  A pre-built version of this would be ideal.

**Comment by karthicksakkaravarti** [comment]
Can you try to install specific version mentioned in pycapy
https://github.com/jordan-wright/pycapy

**Comment by karthicksakkaravarti** [comment]
Added build file of pycapy: https://github.com/vincentdavis/zwifty-packets/blob/main/windows/pcapy.cp38-win_amd64.pyd

**Comment by ruffk** [comment]
I must be really stupid as I just can't figure it out lol!  I put that file in the same folder as all the other .py files and ran Python ZwiftPacketMonitor.py and it said it can't find the .dll pcapy at the import line.

**Comment by ruffk** [comment]
Hi all, checking back on this.  Any suggestions on what / where I'm supposed to do with the file Karthick uploaded?

**Comment by ruffk** [comment]
I found the issue with the compilation under Python 3.10 and Visual Studio.  I actually had to fix a C header file to match the code definition of a method.  I'm closing this issue.

**Comment by vincentdavis** [comment]
@ruffk I am glad you found the solution. I have been really busy with another project.
